# ============================================
# KelasAI - Netlify Configuration
# ============================================

[build]
  command = "npx prisma generate --schema=prisma/schema.prod.prisma && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
